Group 5 initial player
ja3537/polygolf22 pull request #11
Opened 2022-09-17 21:19 UTC by Speculative

Based on 2021 `g2_player`. We made the player aware of sand traps by detecting when the current shot is from a sand trap and changing the calculation of which points are considered "reachable".

2022-09-17 21:22 UTC, Speculative commented
For reference, how the player performs on our group's two proposed maps.

![image](https://user-images.githubusercontent.com/3701912/190876850-2422a06d-de13-4c1c-a925-2632a7b511cc.png)
![image](https://user-images.githubusercontent.com/3701912/190876854-9004e487-b4df-452d-ae38-4c2995981f91.png)

2022-09-18 16:12 UTC, ja3537 requested changes
It looks like you erroneously modified players/g2_player.py when you should modify players/g5_player.py as group 5.

2022-09-18 20:19 UTC, Speculative commented
Whoops, my mistake. Got confused because we're editing g2's code 😅

2022-09-18 21:24 UTC, ja3537 approved these changes

2022-09-18 21:24 UTC, merged