Group 3 2nd deliverable
ja3537/polygolf22 pull request #19
Opened 2022-09-19 17:28 UTC by apapangelapeng

Kmean + Voronoi Diagram + group 2 code

[https://files.slack.com/files-pri/T04116XL2LW-F04398HKLV7/forced_sandtrap_centroids.png](url)

2022-09-19 17:29 UTC, apapangelapeng commented
> Kmean + Voronoi Diagram + group 2 code
> 
> [https://files.slack.com/files-pri/T04116XL2LW-F04398HKLV7/forced_sandtrap_centroids.png](url)

![image](https://user-images.githubusercontent.com/57379824/191077659-b1879ab7-a83d-44d9-92d4-4999f68fd75a.png)

2022-09-19 17:31 UTC, ja3537 requested changes
You need to change only your own source file. You are also changing g2_player here.

2022-09-19 17:33 UTC, noah-codaio commented
> You need to change only your own source file. You are also changing g2_player here.

Sorry @ja3537 we had some confusion here and added the player changes to the wrong file. We will move them over to our g3_player right after class and update the PR so this will be mergable. Sorry for the mistake here!

2022-09-20 18:33 UTC, ja3537 approved these changes

2022-09-20 18:33 UTC, merged